kind = "DojoContract"
class_hash = "0x4da36a34667365460f8a903da1e7539e8ceeeab42411dfcfa1ceae6c38bd1bc"
original_class_hash = "0x4da36a34667365460f8a903da1e7539e8ceeeab42411dfcfa1ceae6c38bd1bc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/types_test-records-11bb3494.json"
reads = []
writes = []
init_calldata = []
tag = "types_test-records"
systems = [
    "create",
    "delete",
]
manifest_name = "types_test-records-11bb3494"
