[package]
name = "dojo_examples"
description = "Dojo example to showcase Dojo features."
version = "1.7.0-alpha.1"	
edition = "2024_07"
cairo-version = "2.12"
license = "MIT"

[cairo]
sierra-replace-ids = true

[dependencies]
openzeppelin = "0.20.0"
starknet = "2.12"

armory = { path = "../game-lib/armory" }
bestiary = { path = "../game-lib/bestiary" }
dojo = "1.7.1"

[[target.starknet-contract]]
build-external-contracts = [
	"dojo::world::world_contract::world",
	"armory::m_Flatbow",
	"bestiary::m_RiverSkale",
]
allowed-libfuncs-list.name = "experimental"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[features]
default = ["dungeon"]
dungeon = []

[profile.saya]
