[workspace]
members = ["armory", "bestiary"]

[workspace.package]
version = "1.7.0-alpha.1"
description = "Example game library for Dojo"
edition = "2024_07"
cairo-version = "2.12"
license = "MIT"

[workspace.dependencies]
starknet = "2.12"
dojo = "1.7.1"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
