kind = "DojoModel"
class_hash = "0x5627ad8b777415eff4116275e8bc0dd640a9a9025b263eeb1c838eecab5a387"
original_class_hash = "0x5627ad8b777415eff4116275e8bc0dd640a9a9025b263eeb1c838eecab5a387"
abi = "manifests/dev/base/abis/models/types_test-Record-21aeac4d.json"
tag = "types_test-Record"
qualified_path = "types_test::models::record"
manifest_name = "types_test-Record-21aeac4d"

[[members]]
name = "record_id"
type = "u32"
key = true

[[members]]
name = "depth"
type = "Depth"
key = false

[[members]]
name = "type_i8"
type = "i8"
key = false

[[members]]
name = "type_i16"
type = "i16"
key = false

[[members]]
name = "type_i32"
type = "i32"
key = false

[[members]]
name = "type_i64"
type = "i64"
key = false

[[members]]
name = "type_i128"
type = "i128"
key = false

[[members]]
name = "type_u8"
type = "u8"
key = false

[[members]]
name = "type_u16"
type = "u16"
key = false

[[members]]
name = "type_u32"
type = "u32"
key = false

[[members]]
name = "type_u64"
type = "u64"
key = false

[[members]]
name = "type_u128"
type = "u128"
key = false

[[members]]
name = "type_u256"
type = "u256"
key = false

[[members]]
name = "type_bool"
type = "bool"
key = false

[[members]]
name = "type_felt"
type = "felt252"
key = false

[[members]]
name = "type_class_hash"
type = "ClassHash"
key = false

[[members]]
name = "type_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "type_deeply_nested"
type = "Nested"
key = false

[[members]]
name = "type_nested_one"
type = "NestedMost"
key = false

[[members]]
name = "type_nested_two"
type = "NestedMost"
key = false

[[members]]
name = "random_u8"
type = "u8"
key = false

[[members]]
name = "random_u128"
type = "u128"
key = false

[[members]]
name = "composite_u256"
type = "u256"
key = false
