[package]
name = "simple"
description = "simple"
version = "1.7.0"	
edition = "2024_07"
cairo-version = "2.12"
license = "MIT"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12"
dojo = "1.7.1"

[[target.starknet-contract]]
