[package]
cairo-version = "2.12"
edition = "2024_07"
name = "types_test"
version = "1.7.0-alpha.1"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12"

dojo = "1.7.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
