name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.85.0

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh

  clippy:
    needs: [fmt]
    runs-on: ubuntu-latest-4-cores
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/clippy.sh

  test:
    needs: [fmt, clippy]
    runs-on: ubuntu-latest-32-cores
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Check env
        run: |
          strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
          ldd --version

      # Currently Katana is downloaded from Dojo, but soon it will be from its own repository.
      - name: Download Katana for integration tests
        run: |
          curl -L https://github.com/dojoengine/dojo/releases/download/v1.4.0/dojo_v1.4.0_linux_amd64.tar.gz -o dojo.tar.gz;
          tar -C /usr/local/bin -xzf dojo.tar.gz

      - name: Run tests
        run: |
          bash scripts/extract_test_db.sh
          cargo nextest run --all-features --workspace --build-jobs 20
