name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.85.0

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh

  clippy:
    needs: [fmt]
    runs-on: ubuntu-latest-4-cores
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Workaround for https://github.com/actions/runner-images/issues/6775
      - run: git config --global --add safe.directory "*"

      - name: Run Clippy
        run: |
          ./scripts/clippy.sh

  test:
    needs: [fmt, clippy]
    runs-on: ubuntu-latest-32-cores
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      # Currently Katana is downloaded from Dojo, but soon it will be from its own repository.
      - name: Download Katana for integration tests
        run: |
          curl -L https://github.com/dojoengine/dojo/releases/download/v1.4.2/dojo_v1.4.2_linux_arm64.tar.gz -o dojo.tar.gz;
          tar -C /usr/local/bin -xzf dojo.tar.gz

      - name: Build Torii binary
        run: |
          cargo build --release --bin torii
          echo "$PWD/target/release" >> $GITHUB_PATH

      - name: Run tests
        run: |
          bash scripts/extract_test_db.sh
          cargo nextest run --all-features --workspace --build-jobs 20
